import webbrowser
from datetime import date
# insert companies name in the yahoo finance URL and download the historical data for the companies from it

d0 = date(1970, 1, 1)
d1 = date.today()

delta = d1 - d0
End = (delta.days * 24 * 60 * 60)
Start = End - 6134336 #31536000 * 4 for the last 4 years

# Start=int(datetime.strptime('1970-01-01', "%Y-%m-%d").replace(tzinfo = timezone.utc).timestamp())
# End = int(datetime.strptime(date.today().strftime('%Y-%m-%d'), "%Y-%m-%d").replace(tzinfo = timezone.utc).timestamp())

for Ticker in "A AAC AAL AAP AAPL AAT AB ABBV ABC ABG ABM ABNB ABR ACGL ACN ACRE ADBE ADI ADM ADP ADPT ADSK AEE AEL AEM \
  AEO AEP AER AFB AG AGI AGM AGO AGRO AHH AHT AI AIG AIT AIV AIZ AJG AKR ALB ALEX ALGN ALK ALL ALLE ALLY ALSN ALTR AMAT AMC\
  AMD AME AMG AMP AMT AMTD AMX AMZN ANET ANF AOS APAM APH AR ARC ARCC ARCO ARDC ARE ARI ARW ASA ASB ASC ASGN ASML ASPN \
  ASR ASX ATEN ATI ATO ATW AU AVB AVD AVG AVGO AVY AWH AWK AXL AXP AXTA AZN AZO BA BAC BAH BAK BAM BAP BAX BBVA BBY BCC \
  BCS BDN BDX BEN BEP BERY BFAM BG BH BHE BHI BHLB BHP BIIB BIO BIP BK BKD BLK BLX BMO BMRA BMS BMY BNK BOH BOOT BR BRFS BRO BRP \
  BRX BSAC BSX BTU BURL BWA BXC BXMT BXP BZH C CAG CAH CB CBL CBU CCI CCK CCS CCU CCZ CDE CDNS CEO CEQP CF CFG CFR CGA CHD \
  CHH CHMI CHRW CHS CHT CHTR CIB CIM CINF CIO CIR CIVI CL CLB CLH CLW CLX CM CMC CMCSA CME CMG CMI CMP CMS CNC CNHI CNI \
  CNO CNP CNQ CNS CNX COF COO COP CORR COST COTY COWN CP CPB CPE CPF CPG CPK CPRT CPT CRL CRM CRS CS CSC CSCO CSL CSTM \
  CSV CTAS CTSH CUDA CUK CUZ CVE CWT CYD CYH D DAL DAR DCI DCO DCT DD DDS DE DECK DEI DELL DFS DG DGX DHI DHT DIS DK DKS \
  DLB DLNG DLR DLTR DNB DO DOOR DRI DSL DSU DSX DTE DV DVA DVN DXCM EA EAT EBAY EBS ECL ED EE EFX EGO EGP EIG EIX EL ELP \
  EME EMN EMO EMR ENS ENVA EOS EPAM EPD EPR EQIX EQR EQS ES ESI ESS ETN EVC EVER EVT EW EXC EXR F FANG FAST FBP FCF FCN FCX \
  FDP FDS FDX FE FET FF FFIV FGL FHN FIS FISV FITB FIX FL FLO FLS FLT FMC FMN FMS FMX FMY FN FNF FOR FR FRC FRT FSM FSS FTI \
  FTK FUL FUN G GAM GBX GD GE GEL GGG GHC GILD GIM GIS GLOB GLW GM GMED GNE GNRC GNW GOLD GOOG GOOGL GPC GPI GPK GPN GRMN \
  GSK GVA GWRE GWW HAL HAS HASI HBAN HBI HCA HD HDB HE HES HIG HII HIO HIVE HIW HL HLF HLT HLX HMC HMN HMY HOLX HP HPE HPP \
  HPQ HR HRB HRL HRTG HSBC HSIC HST HTLF HTZ HUM HVT HYT IBA IBM IBN ICD ICE IDE IDXX IEX IFF IGA IGT ILMN INFY INGR INN INT \
  INTC INTU IP IPG IPGP IPI IR IRM IRS ISRG IT ITW IVR IVZ JBHT JBT JCI JKHY JLL JNJ JNPR JOB JPM K KAR KB KEP KEY KEYS KFS \
  KFY KHC KIM KMB KMX KNX KO KODK KOF KOS KR KRC KRG KSS KWR LADR LBTYA LC LDOS LEE LEG LEU LGI LH LII LKQ LL LLY LMT LNC LNT \
  LOGI LOW LPG LRCX LTC LUV LVS LXP LXU LYB LYV MA MAA MAIN MAN MAR MCD MCHP MCK MCO MCY MDC MDLZ MDT MEG MEI MET META MFC MFG \
  MG MGA MGM MHD MHK MKC MKTX MLI MLM MLR MMC MMI MMM MMP MNP MNST MO MOD MOH MOS MOV MPC MPW MRIN MRK MRO MRVL MSA MSCI MSFT \
  MSI MSM MTDR MTG MTN MTR MTRN MTX MU MUSA MYE NBR NC NCLH NCZ NDAQ NE NEE NEOG NET NEU NFLX NGVC NI NIO NL NLY NM NOC NOK \
  NOV NOW NPK NPO NR NRG NRP NS NSC NTAP NTRA NTRS NTZ NUS NVDA NVO NVRO NWL NWN NX O OB OCN ODFL OFC OHI OII OIS OKE OLP \
  OMC OMI ORAN ORCL ORI ORLY OXM OXY PAA PAI PAM PANW PAR PAY PAYC PAYX PB PBA PBH PBI PBR PCAR PCN PDM PDS PEB PEG PEP \
  PFE PFG PFS PFSI PG PH PHG PHM PII PKG PKI PLD PLOW PM PMF PMT PNC PNNT PNR PNW POR PPG PRGO PRLB PRO PRU PSEC PSF PSX \
  PT PWR PXD PYPL QCOM QRVO QSR QTWO R RBA RCI RCL RCS RDY RE REG REGN REX REXR RF RFIL RFP RGA RGC RGR RHI RJF RL RLI RM \
  RMD ROK ROL ROP RPM RQI RRC RS RSG RVT RWT RY RYAM RYI SAH SAN SAP SAR SBS SBUX SCCO SCHW SCI SE SEAS SEE SEM SF SFE SFL \
  SHG SHW SIG SIGI SIX SJR SKM SKT SKX SLB SLCA SLF SM SMG SMP SNOW SNPS SNV SO SON SONY SPB SPG SPH SPLP SPR SQM SRE SSD \
  SSTK ST STAG STC STM STT STWD STX SU SUI SUP SWK SWKS SWN SWZ SXT SYF SYK T TA TAC TAP TCI TDG TDS TDY TEL TEO TEVA TGH \
  TGI THG THR THS TJX TKC TLK TMHC TMO TMST TMUS TNC TNP TPL TPVG TPX TR TRC TRI TRN TRNO TROW TSCO TSE TSI TSLA TSLX TSM \
  TSN TSQ TTWO TUP TV TVPT TW TWI TWO TXN TXT TYL U UA UAL UBA UBER UL ULTA UMC UNH UNM UNP UPS URI USB USM USNA USPH UTF \
  UTI V VAC VET VFC VGR VIV VLY VMC VMI VMW VOYA VRSK VRSN VSH VTR VVR VZ WAB WAT WBA WBS WCC WCN WDC WEC WFC WGO WHR WIT \
  WLK WMB WMK WNC WNS WOR WPC WRB WRK WSR WST WTI WTM WTS WTW WU WWE WWW WY X XEL XHR XIN XOM XPO XYL YPF ZBH ZION ZM ZTS".split():

    # period1-period2 = the amount of seconds in 1 year. 3.154e^7
    # Remember to Update Period1 & Period2.
    # how it works:
    # for every second that passes , the period1,period2 counter is increased by 1.
    # period 2 = date from 1.1.1970 till today in seconds. ( x )
    # period 1 = date from period2 - 3.154e^7 ( y )
    # period 2 - period 1 == get me all DATA from the latest year.

    webbrowser.open(
        f"https://query1.finance.yahoo.com/v7/finance/download/{Ticker}?period1={Start}&period2={End}&interval=1d&events=history&includeAdjustedClose=true", autoraise=True)
